version: "3"

services:
  be:
    container_name: be
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
      - redis_db
    networks:
      - techStore_network
    volumes:
      - /home/loi/techstore-mybatis/images:/images
  mysql_db:
    image: mysql:8.0.35
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Loi65732102.1
    volumes:
      - /home/loi/mysql_db:/var/lib/mysql
    networks:
      - techStore_network
  redis_db:
    image: redis:7.2.4
    container_name: redis_db
    restart: always
    ports:
      - "6379:6379"
    networks:
      - techStore_network
    volumes:
      - /home/loi/redis_db:/data
networks:
  techStore_network:
    driver: bridge