environment:
  name: prod

spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: root
    url: 'jdbc:mysql://mysql_db:3306/techStore'
    password: Loi65732102.1

upload:
  path: '/images/'

image:
  url: 'http://103.170.246.84/'

redis:
  host: redis_db
  port: 6379
  password: loi65732102
  username: loi
  database: 0
  isAuth: false