environment:
  name: dev

spring:
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    username: root
    url: 'jdbc:mysql://localhost:3306/techStore'
    password: Loi65732102.1

upload:
  path: 'D:\Project\TechStore-Mybatis\static\images\'

image:
  url: 'http://localhost:8080/image/'

redis:
  host: localhost
  port: 6379
  password: loi65732102
  username: loi
  database: 0
  isAuth: false